<div class="item active text-left small" style="padding:10px; font-size=3vmin; margin-top:50px;">
			   		<h4 style="color:navy;font-size:3min; margin-top:-15px;">
						<span class="glyphicon glyphicon-bookmark" style="color:red";></span>
						
							<span class="ads1 text-center">
								DIVINE
							</span>
							<p>
							<span class="ads1 text-center">
								BANQUET
							</span><p>
							<span class="badge" style="background:red;">
									2017
						</span>
						<p>
							<span class="badge" style="background:red;">Theme</spam>
						<p>
							<em class="ads2">HELP IN TIME!</em> 
							
						<p>
						<small class="label label-primary">
								MY YEAR OF ABUNDANT MANIFESTATION 
						</small>
					</h4>

					<br>
					<div class="badge" style="color:white;background:red;">With</div>
					<div class="well" style="margin-top:10px; padding:5px;border:none; background:black; opacity:0.5">
					
						<strong style="color:white; font-size:3.5vmin;">
							Apostle Duncan Ofiyai(G.O.)
						</strong><br>
						
						
					<strong style="color:white; font-size:3.5vmin;">
						Date: 8TH-13th November 2017
					</strong>	
					</div>				
					
					
<div class="fb-share-button" data-href="https://www.facebook.com/lifegateheadquarter" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.facebook.com%2Flifegateheadquarter&amp;src=sdkpreparse">Share</a></div>
					            
</div>