<footer class="container-fluid" style="background:skyblue; border-top:10px solid navy;color:white;">
            <div class="row">
                <div class="col-lg-12">
                    <p class="text-center"style="color:black;">2016-2017&copy; Life Gate Ministries Worldwide.</p>
					<h1 class="text-center">
						<a href="https://web.facebook.com/lifegateheadquarter"><i class="fa fa-facebook"></i>&nbsp;</a>
						<a href="https://twitter.com/lgmww"><i class="fa fa-twitter"></i></a>&nbsp;
						<a href=""><i class="fa fa-youtube"></i></a>&nbsp;
						<a href="contact.php"><i class="fa fa-envelope"></i></a>
					</h1>
					<p class="text-center">
						<a style="color:black;" href="privacy.php">Privacy Policy</a>
					</p>
                </div>
            </div>
        </footer>

    <!-- /.container -->

    <!-- jQuery -->
	    <!-- Bootstrap Core JavaScript -->
    

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>
	
	<script id="dsq-count-scr" src="//www-lgmww-com.disqus.com/count.js" async></script>
	<script src="http://vjs.zencdn.net/5.8.8/video.js"></script>
</body>

</html>
