<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding:0px;">
						
		<div class="text-center">
				<img class="img-responsive img-thumbnail" src="images/misc/b2.jpg">
				<h5 style="font-size:3vmin">LGM Headquarters Church <a href="building.php">View More</a></h5>
		</div>
</div>

<!--
<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" style="padding:0px;">
		<div class="text-center">
				<img class="img-responsive img-thumbnail" src="images/ministrations/choir/ch3.jpg">
				<h5 style="font-size:3vmin">Shepherd Mass Choir <a href="choir.php">View More</a></h5>
		</div>
</div>

-->				
			
<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding:0px;">
		<div class="text-center">
				<img class="img-responsive img-thumbnail" src="images/overflow/g_a1.jpg">
				<h5 style="font-size:3vmin">LGM Interior Overflow <a href="overflow.php">View More</a></h5>
		</div>
</div>


<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding:0px;">
		<div class="text-center">
				<img class="img-responsive img-thumbnail" src="images/ministrations/messages/p1.JPG">
				<h5 style="font-size:3vmin">LGM General Overseer <a href="go.php">View More</a></h5>
		</div>
</div>



<!--
<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" style="padding:0px;">
		<div class="text-center">
				<img class="img-responsive img-thumbnail" src="images/db14.JPG">
				<h5 style="font-size:3vmin">LGM Divine Banquet Photos <a href="banquet.php">View More</a></h5>
		</div>
</div>

<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" style="padding:0px;">
		<div class="text-center">
				<img class="img-responsive img-thumbnail" src="images/w1.JPG">
				<h5 style="font-size:3vmin">LGM - Royal Women <a href="women.php">View More</a></h5>
		</div>
</div>


-->